site_name: PermissionGraph
repo_url: https://github.com/graydenshand/permission-graph

watch:
  - src

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

nav:
  - Getting Started: index.md
  - Reference: reference/